# Generated by Django 4.1.2 on 2022-10-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
