# Generated by Django 4.1.2 on 2022-11-08 08:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='album',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
