# Generated by Django 4.1.2 on 2022-11-08 09:01

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_remove_album_creation_date_album_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='status',
        ),
        migrations.RemoveField(
            model_name='album',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='album',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='album',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
