# Generated by Django 4.1.2 on 2022-11-11 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_status_remove_album_status_changed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('audio_file', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.song'),
        ),
    ]
