# Generated by Django 4.1.2 on 2022-11-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artist_linked_user'),
        ('albums', '0006_song_album_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
    ]
